export const autoBackupPlcmts = [
  "top",
  "top-start",
  "top-end",
  "top-left",
  "top-right",
  "bottom",
  "bottom-start",
  "bottom-end",
  "bottom-left",
  "bottom-right",
  "left",
  "left-start",
  "left-end",
  "right",
  "right-start",
  "right-end",
];
